---
# Get the list of currently active users, these will have the volume set
- name: Get real user list to set volume for
  ansible.builtin.shell:
    cmd: "w -h | awk '{print $1}'"
  register: active_users

- name: Set the volume for default sound sink
  ansible.builtin.shell:
    cmd: "sudo -u {{ item }} pactl -s /run/user/$(id -u {{ item }} )/pulse/native set-sink-volume $( sudo -u {{ item }} pactl -s /run/user/$(id -u {{ item }} )/pulse/native info | awk '/Default Sink:/ {print $3}' ) {{ potos_pulseaudio_default_volume }}"
  register: set_command
  failed_when: set_command.rc != 0
  loop: "{{ active_users.stdout_lines }}"
  changed_when: no


