---
# Get the list of currently active users, these will have the volume set
- name: Get real user list to set volume for
  ansible.builtin.shell:
    cmd: "w -h | awk '{print $1}'"
  register: active_users

- name: Set the volume for default sound sink
  become: yes
  become_user: "{{ item }}"
  ansible.builtin.shell:
    cmd: "pacmd set-sink-volume $( pacmd stat | awk -F': ' '/^Default sink name:/{print $2}' ) {{ potos_pulseaudio_default_volume }}"
  register: set_command
  failed_when: set_command.rc != 0
  loop: "{{ active_users.stdout_lines }}"
  changed_when: no


